### ISSUE TITLE
Arc in board outline imported upside down

### ISSUE THREAD

**Issue by Barabas5532** [easyw/kicadStepUpMod#104]
When I import the attached PCB, one of the arcs in the board outline gets flipped vertically.

I'm using kicad 6.0.0-rc1, FreeCAD 0.19 and kicad StepUp version 10.1.8.1.

![image](https://user-images.githubusercontent.com/28671465/143092837-1c4faec1-d23b-42cd-89e3-1d7da5f89d15.png)
[board.zip](https://github.com/easyw/kicadStepUpMod/files/7590649/board.zip)

**Comment by easyw** [comment]
@Barabas5532 
it should fixed now  https://github.com/easyw/kicadStepUpMod/commit/35e7d52ac1aca1db622567f2a91bd36b16e2b57c
Thx for reporting

**Comment by Barabas5532** [comment]
I can confirm that it is fixed. Thanks!
