### ISSUE TITLE
The sexp parser does not support escaped `"`.

### ISSUE THREAD

**Issue by ithinuel** [easyw/kicadStepUpMod#105]
If a text field contains an escaped double quote the sexp parser crashed reporting an invalid count of brackets.

For example if a footprint contains:

```sexp
    (fp_text user "Active Area 1.3\"" (at -23 -1) (layer "F.Fab")
      (effects (font (size 0.93472 0.93472) (thickness 0.08128)) (justify left bottom))
      (tstamp 60beab46-be82-4200-a5f9-e65c5b3d7176)
    )
```

**Comment by easyw** [comment]
@ithinuel 
thanks for reporting... ATM kv6 is not fully supported... I see if I can handle this user case

**Comment by easyw** [comment]
@ithinuel 
it should be now closed
