### ISSUE TITLE
importing board does not work

### ISSUE THREAD

**Issue by stormyweathers** [easyw/kicadStepUpMod#116]
Hey There,

Thanks so much for making and maintaining this plugin.  Its hugely valuable.
I'm just getting started and I'm having trouble.
I'm able to pull in individual footprints and board outlines, but not the entire board assembly.

When I try to pull in the entire board, I just see an empty screen.
I've checked that the 3D model directory is correct in preferences.

Got any advice about how to proceed?

**Comment by easyw** [comment]
please give me some more info on:
kicad version
freecad version
freecad report panel messages
if possible attache a pcb that doesn't load
