### ISSUE TITLE
Adding tracks on custom layer stackup fails

### ISSUE THREAD

**Issue by kishanmbhat** [easyw/kicadStepUpMod#117]
Hi,

Adding tracks on an 8-layer board with custom layer stackup fails on kicad StepUp version 10.3.4. 

Please find below the log details. Have also attached the test pcb file.

Log Data starts here
------------------------------------
17:13:09  tracks version: 2.4.4
17:13:12  Running the Python command 'ksuToolsAddTracks' failed:
Traceback (most recent call last):
  File "/home/kishan/.FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 3438, in Activated
    add_toberemoved = tracks.addtracks()
  File "/home/kishan/.FreeCAD/Mod/kicadStepUpMod/tracks.py", line 307, in addtracks
    pcb = kicad_parser.KicadFcad(filename)
  File "/home/kishan/.FreeCAD/Mod/kicadStepUpMod/kicad_parser.py", line 561, in __init__
    self._initStackUp()
  File "/home/kishan/.FreeCAD/Mod/kicadStepUpMod/kicad_parser.py", line 659, in _initStackUp
    self._log('stackup info ignored because copper layer {} is not found',
  File "/home/kishan/.FreeCAD/Mod/kicadStepUpMod/kicad_parser.py", line 769, in _log
    getattr(logger,level)('{}{}'.format(self.prefix,msg.format(*arg)))

Replacement index 0 out of range for positional args tuple
------------------------------------
Log Data ends here

Freecad version details
--------------------------------------------
OS: Zorin OS 16 (zorin:GNOME/zorin)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Branch: unknown
Hash: 0d9536ed3e8c7f40197b5606e1b7873625e1d6fe
Python version: 3.8.10
Qt version: 5.12.8
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/India (en_IN)

Kicad version details
-------------------------------------------------
Application: KiCad

Version: 6.0.2-378541a8eb~116~ubuntu20.04.1, release build

Libraries:
	wxWidgets 3.0.4
	libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

Platform: Linux 5.13.0-30-generic x86_64, 64 bit, Little endian, wxGTK, zorin, x11

Build Info:
	Date: Feb 11 2022 08:14:15
	wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.71.0
	OCC: 7.5.2
	Curl: 7.81.0
	ngspice: 31
	Compiler: GCC 9.3.0 with C++ ABI 1013

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

[test.zip](https://github.com/easyw/kicadStepUpMod/files/8124062/test.zip)

**Comment by easyw** [comment]
@kishanmbhat 
it should be fine now
