### ISSUE TITLE
Latest commit breaks importing

### ISSUE THREAD

**Issue by numanair** [easyw/kicadStepUpMod#122]
Hello!
I just updated to the latest commit and I am no longer able to import my design. 
It stops after adding a sketch called PCB_Sketch_draft that appears empty.

KiCad testing (v6.0.3) and Freecad stable v0.19.

Specifically commit c187b5ec032f9c5d8e35530c92cdade54e198025
Tested before that one and it works fine.

**Comment by easyw** [comment]
@numanair 
does my last commit fix it?
could you please add a pcb failing?

**Comment by numanair** [comment]
That fixed it! Thank you!
The board I was testing with is here: https://github.com/numanair/keeby-cat
