### ISSUE TITLE
Any interest of addon KiCAD StepUp addon to GSOC2022 ?

### ISSUE THREAD

**Issue by luzpaz** [easyw/kicadStepUpMod#125]
@easyw would you be open to mentor a student for GSoC to improve this addon?

**Comment by easyw** [comment]
Hi @luzpaz 
thanks for your interest, but I have absolutely no idea what the needs of a GSoC mentor are....

**Comment by luzpaz** [comment]
@yorikvanhavre would you mind sharing a little about what it is to be a mentor?
