### ISSUE TITLE
Board thickness when loading board into FreeCAD

### ISSUE THREAD

**Issue by alowell-ssl** [easyw/kicadStepUpMod#126]
Is there a way to get the correct board thickness when importing the board into FreeCAD?  I tried changing the board thickness in Kicad (via "physical stackup" menu), but this did not affect the board thickness when importing to FreeCAD.

**Comment by easyw** [comment]
for a issue report please add:
1) your kicad full version
2) your freecad full version
3) your StepUp WB version
and please add
4) a failing example board

After that, it seems that in some version of kicad v6 physical stackup will not adjust the internal value of pcb thickness
If you open the 'kicad_pcb' file in a text editor, which is the thickness value you find? (see here the first 5 lines of a board text file)
```
(kicad_pcb (version 20211014) (generator pcbnew)

  (general
    (thickness 1.6)
  )


```
