### ISSUE TITLE
Can not find custom 3d model path in FreeCAD

### ISSUE THREAD

**Issue by bookshiyi** [easyw/kicadStepUpMod#128]
Hello,
System: Manjaro latest version
KiCad : 6.0.4
FreeCAD: 0.19
kicadStepUpMod: latest version

When I load pcb from KiCad to FreeCAD, I received some error message about kicadstepupmod can not find 3d model which in my user path(not  KiCad system path).
 
```
 missing module(s)
... searching path:
/usr/share/kicad/3dmodels/
/home/USER/repos/kicad_library/3dmodel/
... missing module(s) '.step' or '.stp' or .iges' or '.igs'
"${KICAD6_USER_3DMODEL_DIR}/TF-SMD_L14.8-W14.5-H1.9-P1.1.step" (.stp or .step)
"${KICAD6_USER_3DMODEL_DIR}/TF-SMD_L14.8-W14.5-H1.9-P1.1.wrl" (.stp or .step)

. . . missing 10 model(s)
```

I have configured `KICAD6_USER_3DMODEL_DIR` both in KiCad and FreeCAD， like this:

In KiCad
![image](https://user-images.githubusercontent.com/14087838/163949159-25bb949f-316d-479f-bda8-2db8c0b19117.png)

In FreeCAD
![image](https://user-images.githubusercontent.com/14087838/163948915-d59b13e2-b987-4a94-9f61-cfa3157ea4f7.png)

Thanks.

**Comment by easyw** [comment]
@bookshiyi 
from your log  it seems there is something strange in the secondary 3D folder location:

```
/home/`USER`/repos/kicad_library/3dmodel/
```
it seems there is a  backtick character before U and before / in your secondary location string...

**Comment by bookshiyi** [comment]
> @bookshiyi from your log it seems there is something strange in the secondary 3D folder location:
> 
> ```
> /home/`USER`/repos/kicad_library/3dmodel/
> ```
> 
> it seems there is a backtick character before U and before / in your secondary location string...


Sorry, I just want to mask the username.
In the actual log from kSU, it is indeed displayed the path I filled in FreeCAD settings.

**Comment by easyw** [comment]
but do you have i.e. ths model in your system?

/home/USER/repos/kicad_library/3dmodel/TF-SMD_L14.8-W14.5-H1.9-P1.1.step
?
Which is your USER correspondent in your case?

${KICAD6_USER_3DMODEL_DIR}/TF-SMD_L14.8-W14.5-H1.9-P1.1.step

**Comment by bookshiyi** [comment]
Hi,

I indeed have the 3d model `TF-SMD_L14.8-W14.5-H1.9-P1.1.step`  in  the path `/home/USER/repos/kicad_library/3dmodel/TF-SMD_L14.8-W14.5-H1.9-P1.1.step`.

I can find it  both path `/home/USER/repos/kicad_library/3dmodel/TF-SMD_L14.8-W14.5-H1.9-P1.1.step` and `${KICAD6_USER_3DMODEL_DIR}/TF-SMD_L14.8-W14.5-H1.9-P1.1.step` in KiCad.

My custom 3d model only not work with kicadStepUp in FreeCAD.

Thanks.
BR

**Comment by easyw** [comment]
@bookshiyi 
would you mind to attach a minimal kicad_pcb sample file (zipped) with a failing 3d loading file?

**Comment by easyw** [comment]
@bookshiyi 
I'm closing it. If you need more assistance, please feel free to reopen it.
