### ISSUE TITLE
 Running the Python command 'ksuToolsOpenBoard' failed

### ISSUE THREAD

**Issue by yueduz** [easyw/kicadStepUpMod#130]
```
opening /home/lei/kicad/吹奏乐器/吹奏乐器.kicad_pcb
09:13:23  my file path /home/lei/kicad/吹奏乐器
09:13:23  opening Transaction 'opening_kicad'
09:13:23  grid origin found @ (-140, 50)
09:13:23  PCB Loader 
09:13:23  pcb thickness 1.6mm
09:13:23  kicad_pcb version 20211014
09:13:23  parsing
09:13:23  4 edge segments
09:13:23  aux_axis_origin[140, 50]
09:13:23  grid_origin[140, 50]
09:13:23  parsing&building time 0.002
09:13:23  Running the Python command 'ksuToolsOpenBoard' failed:
Traceback (most recent call last):
  File "/home/lei/.FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 927, in Activated
    kicadStepUptools.onLoadBoard()
  File "/home/lei/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 6810, in onLoadBoard
    modules,nsk = DrawPCB(mypcb,SketchLayer,override_pcb,keep_pcb_sketch)
  File "/home/lei/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 12393, in DrawPCB
    if p.drill[0] >= min_drill_size or p.drill[1] >= min_drill_size:
  File "/home/lei/.FreeCAD/Mod/kicadStepUpMod/fcad_parser/sexp_parser/sexp_parser.py", line 147, in __getitem__
    v = self._value[key]

(0,)
```

OS: Arch Linux (GNOME/gnome-xorg)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24415 (Git)
Build type: Release
Branch: makepkg
Hash: 476ecf091941bead59b14e44afa6064d5a66afa3
Python version: 3.10.4
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.5.3
Locale: Chinese/China (zh_CN)
kicad StepUp version 10.4.3
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
Application: KiCad PCB 编辑器

Version: (6.0.4), release build

Libraries:
	wxWidgets 3.0.5
	libcurl/7.83.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0

Platform: Linux 5.17.5-arch1-1 x86_64, 64 bit, Little endian, wxGTK, gnome-xorg, x11

Build Info:
	Date: Mar 18 2022 08:05:28
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.78.0
	OCC: 7.5.3
	Curl: 7.82.0
	ngspice: 36
	Compiler: GCC 11.2.0 with C++ ABI 1016

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

I have a problem importing this file. The other files have no title. But there's nothing wrong with this file in KICAD.
[吹奏乐器pcb.zip](https://github.com/easyw/kicadStepUpMod/files/8595429/pcb.zip)

**Comment by easyw** [comment]
hi @yueduz 
the issue is in parsing the pad 1 of BT1 fp
The pad has a drill offset but without a drill, which is not (ATM) handled by the ksu parser
I see if I can patch this for the pdb loader... for tracks loader it would take a bit longer
here the pcb with the pad 'reworked'
[吹奏乐器-no-offset.zip](https://github.com/easyw/kicadStepUpMod/files/8596581/-no-offset.zip)

**Comment by yueduz** [comment]
It worked. Thank you very much
