### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by leoheck** [easyw/kicadStepUpMod#134]
Hello, @easyw ! Mostly all tooltips on this module have `ksu` in front of them. It would be much helpful to have this string removed. What do you think? I can make a PR if you would accept this idea. Thanks.

**Comment by easyw** [comment]
Hi @leoheck 
not all the commands that have a similar icon will act exactly as the main FC commands... that is why I places 'ksu' in front of the command...
If you remove 'ksu' in front of the only 'basic' command which will act exactly as FC std command, that would be a merge-able PR.

**Comment by easyw** [comment]
the fourth point is exactly what I did adding 'ksu' to the tooltips.

I think if you remove 'ksu' in front of the only 'basic' command which will act exactly as FC std command, that would be a merge-able PR. It is only needed to check in the code if the command is the basic or is modified.

**Comment by leoheck** [comment]
Oh, I did not explain it right. My bad. 
I mean, you put this in the tooltip "Title". 
In the first place, which is bold. I wanted to suggest adding a line at the end. 
So, the title (the tool name) will to be simple and be easy to read.

**Comment by easyw** [comment]
@leoheck 
sorry for misunderstanding you...
A pr to remove 'ksu' in front of the title would be useful.

**Comment by easyw** [comment]
@leoheck 
it should be fine now

**Comment by leoheck** [comment]
Oh, did you do that already? Nice and sorry for not doing this idea before you. 

Those fixed tooltips are great and clean. Thanks a lot.


I still have some suggestions, hope I am not bothering you.

`ksu Tools` to `KSU Tools`

There are some tooltips that do not need a description since the title says it all. 

Here, it can be improved too like
![image](https://user-images.githubusercontent.com/1277920/175956732-bccb4a5e-5ead-4b42-8094-ddd6cfe58012.png)
```
Bolt title: Add PCB Tracks
Description: This operation can be heavy for some computers. Save your design first.
```

![image](https://user-images.githubusercontent.com/1277920/175957373-300ede1e-6db2-46c1-b2e0-1e5a05234482.png)
```
Bolt title: Add PCB Silkscreen
Description: This operation can be heavy for some computers. Save your design first.
```

![image](https://user-images.githubusercontent.com/1277920/175957653-53890715-0dd9-443f-b7aa-333941bf1029.png)
```
Bolt title: Loop Selection
Description: Loop selection on an XY outline
```
To be honest I have no idea what this operation does yet. 

![image](https://user-images.githubusercontent.com/1277920/175958148-3fbabf84-183d-4982-a2ae-11b5939e8485.png)
```
Bolt title: KSU Selection Extrude
```

![image](https://user-images.githubusercontent.com/1277920/175958324-b76516ac-ce8f-4cf6-b5a0-fc05db8633a1.png)
```
Bolt title: KSU Validade Sketch
```

![image](https://user-images.githubusercontent.com/1277920/175958758-40f57017-9837-4495-adfa-891c7d20985e.png)
```
Bolt title: RF Polyline Sketch
```

This is extra (off-topic), saw it now while checking the tooltips.
Some icons are replicated in the toolbar.
This two 
![image](https://user-images.githubusercontent.com/1277920/175959289-572370a4-46f8-4852-b8d5-5e039ee13211.png)
This one, too.
![image](https://user-images.githubusercontent.com/1277920/175959366-3379a9a1-0ce0-4ae6-9162-a4cb5b116d98.png)

**Comment by easyw** [comment]
> This is extra (off-topic), saw it now while checking the tooltips.
> Some icons are replicated in the toolbar.
> This two

the replicated icons are in different toolbars... this allows the user to hide some and keep only some commands visible

**Comment by leoheck** [comment]
Ok, this is what I thought, but I wanted to check anyways. Thanks for explaining it to me.

I just thought the KSU toolbar is a bit busy.

If you look for a different solution, you could have a toolbar with only these things. So you don't need to replicate the items.

**Comment by leoheck** [comment]
Sure, no problem I will work on that.
--
Leandro Heck
