### ISSUE TITLE
Castelated vias

### ISSUE THREAD

**Issue by leoheck** [easyw/kicadStepUpMod#137]
Hello easyw!

Does KicadStepUp handle castellated vias?
I was trying to import tracks. And then got this.

![image](https://user-images.githubusercontent.com/1277920/176774203-a9e85b10-4a3f-4348-8c94-ce6adf4cbd2b.png)

this is the result, I dot have wires connected to the vias
![image](https://user-images.githubusercontent.com/1277920/176774046-57ac1973-99da-440e-90c8-4b62ad46cc9c.png)

**Comment by leoheck** [comment]
Actually, it imports vias fine. But in the end, something happens that it cannot add. Maybe it is not being able to cut them in half.

**Comment by leoheck** [comment]
Ah, I used the wrong word. I am talking about pads, not vias, sorry.

Here in this design, I am using a standard connector to make these castellated holes. However, just one of those pads have the castellated propertie enabled since Kicad is not fully working/using them. Ony the first castellated holes hax this property. but it is not keeping the castellated pad there.

Do you have any advice for me to check or do to make this work?

**Comment by easyw** [comment]
> Do you have any advice for me to check or do to make this work?

if you post a failing example I could have a look at...
it simply should work (at least it worked)
https://github.com/easyw/kicadStepUpMod/issues/123
