### ISSUE TITLE
board import does not handle bezier curves

### ISSUE THREAD

**Issue by morganrallen** [easyw/kicadStepUpMod#14]
KiCAD support's bezier curves? who knew!

Well, it appears when importing from DXF, KiCAD will create bezier curves but StepUp doesn't seem to like or handle them.

![image](https://user-images.githubusercontent.com/22881/55694627-d3b7ff80-5969-11e9-9c45-5b9a2a3f84ac.png)

Note the two handle points on the selected curve.

![image](https://user-images.githubusercontent.com/22881/55694636-e29eb200-5969-11e9-9cae-423065c721fe.png)

All source files can be found here, https://gitlab.com/morganrallen/kickbadge/commit/c72e021e5a41f7ae2860fb3e7477c6b5a273467b

**Comment by easyw** [comment]
@morganrallen thanks for let me know about the new bspline support for edge-cut from kicad...
I'm going to see f I can support it...
BTW the correct workflow would be to start your design in FC and not importing a dxf in kicad ...
1) design your edge in FC (or import your dxf in FC) 
2) push the edge to kicad using stepup
3) continue your job in kicad
NB please remember to add reference in kicad like i.e. a grid origin to be use as a mutual reference between kicad and freecad.

**Comment by easyw** [comment]
Hi @morganrallen 
please have a try with the new update...
StepUp now can import also splines and push back the edge to KiCAD if required.
Still is a first implementation that can be improved.

**Comment by easyw** [comment]
![bsplines](https://user-images.githubusercontent.com/3032347/56151410-751a0380-5fb1-11e9-8fc7-83d9833fea54.png)

**Comment by morganrallen** [comment]
Hey Maurice, thanks a lot, it's looking great now.
