### ISSUE TITLE
3D model of the footprints not imported with "load board" function

### ISSUE THREAD

**Issue by loiiiic** [easyw/kicadStepUpMod#140]
Hello,

When using the "Load board" function with a *.kicad_pcb file (KiCad 6), the 3D models of the components are not found.
I get this error :

```shell
11:46:42  step-module-replaced Resistor_SMD.3dshapes/R_0805_2012Metric.wrl
11:46:42  model name R_0805_2012Metric
11:46:42  error missing "${KICAD6_3DMODEL_DIR}/Resistor_SMD.3dshapes/R_0805_2012Metric.wrl"
11:46:42  added 0 model(s)
11:46:42  running time: 0.117sec
11:46:42  missing models
11:46:42  "${KICAD6_3DMODEL_DIR}/Resistor_SMD.3dshapes/R_0805_2012Metric.wrl" (.stp or .step)
11:46:42  
11:46:42  searching path
11:46:42  /usr/share/kicad/3dmodels/
```
I set up the path like this in FreeCad:

![path](https://user-images.githubusercontent.com/105224252/179954272-b05c423b-c2a1-4e4b-a1b5-a636af4840ad.PNG)

If I copy the 3dmodels folder from /usr/share/kicad to /home/loiiiic/Documents/ and declare the paths below, it works. There is something I don't understand.

![Capture 2](https://user-images.githubusercontent.com/105224252/179954437-a5f89e64-5529-4cd0-9a3d-79ab489f6eed.PNG)

Thank you for your feedback.

**Comment by easyw** [comment]
@loiiiic 
1) I'm not sure if it can be the culprit, but could you remove the last slash '/' at the end of the first field '/usr/share/kicad/3dmodels/'
2) it could be a permissions issue... can FC access and read those 3D models? (i.e. import a 3d model manually using FC?)

**Comment by easyw** [comment]
@loiiiic 
this seems an issue in how FC can read the folders (is FC installed or AppImage or Flatpack?)
or an issue in kicad installation process...
Can you read/acess the '/usr/share/kicad/3dmodels/Resistor_SMD.3dshapes/R_0805_2012Metric.step' i.e. in a text editor?

**Comment by easyw** [comment]
> If I click on the three small dots to look for the path, **the kicad folder is not present** in the window

that is strange

**Comment by loiiiic** [comment]
@easyw 

I can open /usr/share/kicad/3dmodels/Resistor_SMD.3dshapes/R_0805_2012Metric.step with a text editor.

Freecad was installed via Flatpak (version 0.20).

I just installed it via apt (version 0.19) and it works.

**Comment by easyw** [comment]
thanks for your feedback... it seems an issue of flatpack then
may you try FC0.20 via AppImage?
https://github.com/FreeCAD/FreeCAD/releases/download/0.20/FreeCAD-0.20.0-Linux-x86_64.AppImage

**Comment by loiiiic** [comment]
@easyw 

It is working with the AppImage, I will stay with the AppImage.

Thank you for your help and for your addon! :-)
