### ISSUE TITLE
The same Label Name in FreeCad as in the Net Name in KiCAD

### ISSUE THREAD

**Issue by RolandWa** [easyw/kicadStepUpMod#147]
Hi All,

Please update the track importer, to add the Net Name from the KiCAD to the Label name in FreeCAD

Net name in FreeCad
![image](https://user-images.githubusercontent.com/28116146/187361360-b92dbf30-f4ae-467d-a261-54e936132976.png)

Net Name in KiCAD

![image](https://user-images.githubusercontent.com/28116146/187361483-330e8c0b-5714-4dd0-a7f0-220842a313f6.png)

**Comment by easyw** [comment]
@RolandWa 
this is not possible because kSU is building FC track item as a compound of pcb tracks

you may have a look at [fcad_pcb](https://github.com/realthunder/fcad_pcb) top achieve a selective loading
