### ISSUE TITLE
Sketch failing to export to Kicad

### ISSUE THREAD

**Issue by Shackmeister** [easyw/kicadStepUpMod#149]
Please try exporting the attached sketch to kicad edgecut.
[KSU_Export_error.zip](https://github.com/easyw/kicadStepUpMod/files/9579428/KSU_Export_error.zip)

**Comment by easyw** [comment]
@Shackmeister 
for me it is working on FC 0.19.4; 0.20.1; 0.21-daily on win
I'm attaching a resulting board

[test-push-kv6-kicad_pcb.zip](https://github.com/easyw/kicadStepUpMod/files/9584306/test-push-kv6-kicad_pcb.zip)

P.S. why are you not using grid origin as reference? your sketches are always so far from the center ...

**Comment by Shackmeister** [comment]
Tried again, and now it works.
Will reopen the issue if it shows again.
