### ISSUE TITLE
Issues found when doing compound and single copy

### ISSUE THREAD

**Issue by leoheck** [easyw/kicadStepUpMod#151]
Hey easyw, got this issue when trying to make a single object from a board.

```
22:56:42  PoM not present
22:56:42  using 'Part' container and 'Links'
22:56:42  kicad_parser_version 2.1.6
22:56:42  FC Version 021-30430
22:56:42  kicad StepUp version 10.7.2
22:56:42  tolerance on vertex applied
22:56:42  applying Materials to Shapes
22:56:42  your home path is /home/lheck
22:56:42  export to STEP False
22:56:42  Tabified done !
22:56:42  done!
22:56:42  doing compound and single copy
22:56:44  Running the Python command 'ksuToolsMakeCompound' failed:
Traceback (most recent call last):
  File "/home/lheck/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUpCMD.py", line 1134, in Activated
    kicadStepUptools.group_part()
  File "/home/lheck/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 2389, in group_part
    recurse_node(obj,obj.Placement, sc_list)       
  File "/home/lheck/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 1877, in recurse_node
    recurse_node(o,new_plcm,scl)
  File "/home/lheck/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 1885, in recurse_node
    simple_cpy_plc(o,plcm)
  File "/home/lheck/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 1843, in simple_cpy_plc
    FreeCADGui.ActiveDocument.ActiveObject.LineColor=FreeCADGui.ActiveDocument.getObject(obj.Name).LineColor
'Gui.ViewProviderDocumentObject' object has no attribute 'LineColor'
```

Maybe this LineColor could be ignored since it can assume black or something...

**Comment by leoheck** [comment]
It could generate the compound by commenting out these 3 lines.

![image](https://user-images.githubusercontent.com/1277920/191880072-0cba9f97-8029-4652-9a88-d97c10097af9.png)

there is this new line 1842 that I added to track the problematic model.

**Comment by easyw** [comment]
@leoheck 
could you post a minimal work example having this issue?

**Comment by leoheck** [comment]
I am going to try. I am not sure if I can reproduce it anymore.

However, I could track a part (a JST connector taken from the internet) that is not keeping the same colors as the others. It is turning green in the resulting part while others are turning gray. But sure, I will try to share something that you can taste.

**Comment by leoheck** [comment]
I still have to separate this minimal example for you.

But I am using a better approach since another board was having issues in the same place of the code but with the ShapeColor now.

```python
   try:
      FreeCADGui.ActiveDocument.ActiveObject.ShapeColor=FreeCADGui.ActiveDocument.getObject(obj.Name).ShapeColor
   except:
      print(obj.Name + "does not have ShapeColor")
   try:
      FreeCADGui.ActiveDocument.ActiveObject.LineColor=FreeCADGui.ActiveDocument.getObject(obj.Name).LineColor
   except:
      print(obj.Name + "does not have LineColor")
   try:
      FreeCADGui.ActiveDocument.ActiveObject.PointColor=FreeCADGui.ActiveDocument.getObject(obj.Name).PointColor
   except:
      print(obj.Name + "does not have PointColor")
   try:
      FreeCADGui.ActiveDocument.ActiveObject.DiffuseColor=FreeCADGui.ActiveDocument.getObject(obj.Name).DiffuseColor
   except:
      print(obj.Name + "does not have DiffuseColor")
   try:
      FreeCADGui.ActiveDocument.ActiveObject.Transparency=FreeCADGui.ActiveDocument.getObject(obj.Name).Trasnparency
   except:
      print(obj.Name + "does not have Transparency")
```

**Comment by easyw** [comment]
> But I am using a better approach

could you post the printing result of:
```
print(FreeCAD.ActiveDocument.ActiveObject.Name, FreeCAD.ActiveDocument.ActiveObject.TypeId)
print(obj.Name,obj.TypeId)
```
placed at line 1842 of your screenshot?

**Comment by easyw** [comment]
@leoheck 
I have a little suspect... are you using assembly4, aren't you?
That is a completely different approach... I can solve this, but I need to know all the environment!

**Comment by leoheck** [comment]
Yeh, I am using Assembly 4. But I also moved the board to another file that does not have Part+Model objects to generate a single file of a PCB. 

Just having the workbench installed interfere with the operation?

My environment is this one, forgot to share, sorry.

[code]
OS: Ubuntu 22.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.30430 (Git) AppImage
Build type: Release
Branch: master
Hash: 9e1ed4a68ad43309c2b38f7f5efbb1feac4323cb
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Part-o-magic.backup1662467294.9039905
  * A2plus 0.4.59
  * Curves 0.5.8
  * fasteners 0.4.6
  * lattice2 1.0.0
  * Assembly4 0.12.4
  * kicadStepUpMod 10.15.1
  * Help 1.0.3
[/code]

**Comment by easyw** [comment]
> But I also moved the board to another file that does not have Part+Model objects to generate a single file of a PCB.

but you copied the board from an assembly4 model

`easyw> D8_DPY0002A_ASM_5F196AB1_ln_001 App::Link`
in fact AppLink object is coming from A4 object inside a Model

What I can do is fixing this issue creating a copy but without the colors...
Even Part WB is not able to make a copy with colors... (Part Menu, Create a Copy, Create simple copy)
You need to move to FC LinkBranch to get a single copy with colors of AppLink object(s)

**Comment by leoheck** [comment]
I imported this board, from the kicad_pcb file directly using KicadStepUp

It gives me the same messages.
![image](https://user-images.githubusercontent.com/1277920/192286003-345557b0-9426-49c0-82eb-af4fb9734d12.png)

```
10:13:10  Shape does not have Transparency
10:13:10  easyw> Shape_cp Part::Feature
10:13:10  easyw> Shape Part::Feature
```

This transparency issue happens on all parts. Other issues are not so often (ShapeColor, LineColor, PointColor, DiffuseColor)

AH, there is a typo here. I think I did not touch this line, but I will have to check the master version.
![image](https://user-images.githubusercontent.com/1277920/192286342-cc712af0-d042-453b-bce9-b68a145cd7b4.png)

**Comment by leoheck** [comment]
This typo was mine. =/

**Comment by leoheck** [comment]
![image](https://user-images.githubusercontent.com/1277920/192287548-d50e744f-03f0-44b6-b26c-f8a09662bdfb.png)

Now, without the typo. Some parts are good, some are not. 

If you are saying that you are going to remove the color when the part is not Part::Feature then It looks good to me.
This makes sense, since I don't want to lose all the color. 
Maybe a message saying that it is missing a Part::Feature.
But I have no idea why some objects are App:Link. There is nothing to do with Asm 4.

**Comment by leoheck** [comment]
Maybe this is good

```python
   if obj.TypeId == "Part::Feature":
      FreeCADGui.ActiveDocument.ActiveObject.ShapeColor=FreeCADGui.ActiveDocument.getObject(obj.Name).ShapeColor
      FreeCADGui.ActiveDocument.ActiveObject.LineColor=FreeCADGui.ActiveDocument.getObject(obj.Name).LineColor
      FreeCADGui.ActiveDocument.ActiveObject.PointColor=FreeCADGui.ActiveDocument.getObject(obj.Name).PointColor
      FreeCADGui.ActiveDocument.ActiveObject.DiffuseColor=FreeCADGui.ActiveDocument.getObject(obj.Name).DiffuseColor
      FreeCADGui.ActiveDocument.ActiveObject.Transparency=FreeCADGui.ActiveDocument.getObject(obj.Name).Transparency
   else:
      print("simple_cpy_plc: {obj_name} ({obj_id}) does not have colors information".format(obj_name=obj.Name, obj_id=obj.TypeId))
```

It gives me a good result. But it loses the colors where they are in the first place
![image](https://user-images.githubusercontent.com/1277920/192289822-9f45d33c-5ff0-43de-b806-88eb6638ff81.png)


In this board, the only difference I noticed was a spacer changing color despite all of the given messages.

![image](https://user-images.githubusercontent.com/1277920/192290291-7da40d08-20c1-48ef-8b0f-6111462aa0cf.png)

**Comment by easyw** [comment]
> In this board, the only difference I noticed was a spacer changing color despite all of the given messages.

send me a minimal board with more than one spacer and te STEP spacer model

**Comment by easyw** [comment]
> I imported this board, from the kicad_pcb file directly using KicadStepUp
> 
> It gives me the same messages.

from your screenshot it is clear you don't follow the suggestions you get from the wb messages (nor read the kSU cheatsheet)
![warnings](https://user-images.githubusercontent.com/3032347/192378063-55b68050-9230-4a66-a4f9-4cfd46184cc7.png)

probably this is your main issue

**Comment by leoheck** [comment]
it is clear that I cannot read this yellow thing

**Comment by leoheck** [comment]
also, I don't want to change my preferences. this function can work with having this set as I showed before.

**Comment by leoheck** [comment]
anyways, what is your point here?

**Comment by leoheck** [comment]
If it is required, please, set it yourself, change my settings file before running this WB and then revert back after.. 
This is a python program, you can do anything you want. Why limit this to user behavior?

Save a copy of the settings...
Set whatever is required.
Run the command
Revert the settings...

**Comment by leoheck** [comment]
> (nor read the kSU cheatsheet)
 
Of course not, I would not read that stupid manual. Because it is unreadable.

**Comment by leoheck** [comment]
I cannot read this, what does it say? Yellow is kind of invisible to my eyes.

Instead of the WB depending on the stupid user since it is a program, it could do something like this things:

You can bkp my config file.
Then change whatever you want.
Then execute the action
Then revert the config file.

**Comment by easyw** [comment]
> Instead of the WB depending on the stupid user since it is a program, it could do something like this things:

1) read the manual
2) the WB programmer (me) cannot and doesn't want to force people in setting the environment ... everything is on user's side
3) backup the config file, and at the end revert it doesn't work... imagine if the import operation fails for some reason... your original config file is lost
4) you open issues without giving:
   - a full environment information
   - a minimal failing example

Please come back when you have a failing sample.
