### ISSUE TITLE
footprint don't load layers

### ISSUE THREAD

**Issue by jneiva08** [easyw/kicadStepUpMod#164]
Hi,

I'm using kicadStepUpMod v10.17.0 with FreeCAD c0.20.2. My KiCad version is v7.0.1 and OS is Linux Mint 21.1

When try to load a footprint it only shows the pad's, don't load F.Fab or F.Silkscreen, as you can see in the screenshot.
The footprint i used is the following:  [Battery_THT_18650.kicad_mod.txt](https://github.com/easyw/kicadStepUpMod/files/10985371/Battery_THT_18650.kicad_mod.txt)

Screenshot:

![image](https://user-images.githubusercontent.com/8236353/225468767-fa85cd01-3442-4a56-85ff-fb7e5903c55f.png)

**Comment by easyw** [comment]
@jneiva08 
thanks for giving all the infos...
ATM StepUp doesn't parse correctly kv7 footprints for drawing layers ...
I'm working on an alternative parser for footprint loader... I will update it shortly

**Comment by jneiva08** [comment]
Thanks for explaining.

I'm trying to convert to two step to make a PAD and its giving error.
Is better to open a new issue? or can post here?

**Comment by easyw** [comment]
> I'm trying to convert to two step to make a PAD and its giving error.
> Is better to open a new issue? or can post here?

please open a different issue
