### ISSUE TITLE
Export to .step and .stp

### ISSUE THREAD

**Issue by romain145** [easyw/kicadStepUpMod#18]
More a feature request than a real issue but would it be possible to allow exporting a STEP object to a .stp file as well as a .step file?
FreeCAD allow export to STEP (*.stp, *.step) but the button in kicad StepUp tools only allows for *.step (which is confusing as some files have a .stp extension, and therefore are not shown in the window).

**Comment by easyw** [comment]
@romain145 
it should be now allowed :smile: 
[OpenVertexes for constrainator, *.stp allowed on exporting ](https://github.com/easyw/kicadStepUpMod/commit/43f5846c1e9084fbb0c510951049fd4f002d6e19)
