### ISSUE TITLE
Failed to import dxf file

### ISSUE THREAD

**Issue by HaydenHu** [easyw/kicadStepUpMod#181]
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Chinese/China (zh_CN)
[/code]

```
21:27:49  filename = test-B_Silkscreen
21:27:49  loading... 
21:27:49  opening D:/HAYDEN/CAD/KICAD/kicad6/test/test-B_Silkscreen.dxf...
21:27:49  There has been an error:
21:27:49  Unable to identify DXF file version
21:27:49  Running the Python command 'ksuToolsAddSilks' failed:
Traceback (most recent call last):
  File "D:\SOFTWARE\FreeCAD_0.21.0-Windows-x86_64\FreeCAD_0.21.0-2023-08-02-conda-Windows-x86_64-py310\Mod\kicadStepUpMod-master\.\kicadStepUpCMD.py", line 4210, in Activated
    makefacedxf.makeFaceDXF()
  File "D:\SOFTWARE\FreeCAD_0.21.0-Windows-x86_64\FreeCAD_0.21.0-2023-08-02-conda-Windows-x86_64-py310\Mod\kicadStepUpMod-master\.\makefacedxf.py", line 184, in makeFaceDXF
  File "D:\SOFTWARE\FreeCAD_0.21.0-Windows-x86_64\FreeCAD_0.21.0-2023-08-02-conda-Windows-x86_64-py310\Mod\Draft\importDXF.py", line 2766, in insert
    processdxf(doc, filename)
  File "D:\SOFTWARE\FreeCAD_0.21.0-Windows-x86_64\FreeCAD_0.21.0-2023-08-02-conda-Windows-x86_64-py310\Mod\Draft\importDXF.py", line 2136, in processdxf
    drawing = dxfReader.readDXF(filename)
  File "D:\SOFTWARE\FreeCAD_0.21.0-Windows-x86_64\FreeCAD_0.21.0-2023-08-02-conda-Windows-x86_64-py310\Mod\Draft-dxf-importer-master\dxfReader.py", line 399, in readDXF
    (infile, drawing) = sm.run((infile, None))

cannot unpack non-iterable bool object
```
[test.zip](https://github.com/easyw/kicadStepUpMod/files/12419682/test.zip)

**Comment by easyw** [comment]
@HaydenHu 
from your traceback, you miss the FC dxf legacy importer (or you miss to configure FC to use it)
Please follow the kSU cheatsheet for silks importing
[test-silks.zip](https://github.com/easyw/kicadStepUpMod/files/12448205/test-silks.zip)
![silks](https://github.com/easyw/kicadStepUpMod/assets/3032347/09762ce4-0fcf-4536-8122-ea17d97ace41)
![fc-dxf-import](https://github.com/easyw/kicadStepUpMod/assets/3032347/60c72733-9b0b-464c-ba82-a6328e66d700)

**Comment by HaydenHu** [comment]
![image](https://github.com/easyw/kicadStepUpMod/assets/30103277/df1fb7f0-ea68-434f-b734-d5cfa5c238e1)
That's how it's set up, and the same error occurs

**Comment by DeepCoreSystem** [comment]
I too have this problem ... and so far the same settings as above and the cheat sheet. I suspect something changed at FreeCAD with the DXF importer

**KiCAD Settings**
![KiCAD_Settings](https://github.com/easyw/kicadStepUpMod/assets/3703938/020fbb95-021c-4ecd-b6f4-da460ed2479d)

**FreeCAD DXF Settings**
![FC_DXF_Settings](https://github.com/easyw/kicadStepUpMod/assets/3703938/330620d7-5e84-4766-8722-f3b940c6449d)

**FreeCAD silkscreen import failure message**
![FC_DXF_failure](https://github.com/easyw/kicadStepUpMod/assets/3703938/daae900d-35f0-4e2c-ba17-0710712ad1dd)

`
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * ToolbarStyle
  * A2plus 0.4.60n
  * Defeaturing 1.2.0
  * kicadStepUpMod 10.19.4
  * Assembly4 0.50.2
  * Manipulator 1.5.0
  * fasteners 0.4.62

`

**Comment by DeepCoreSystem** [comment]
@easyw : It really seems to be a problem on FreeCAD side, becaus I made a new, empty FC file and tried to import the DXF (with the legacy importer) from above test file of @HaydenHu and got the following error:

```
17:48:04  opening /home/pde/Downloads/test/test-F_Silkscreen.dxf...
17:48:04  There has been an error:
17:48:04  Unable to identify DXF file version
17:48:04  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_FreeCAXl4oNg/usr/Mod/Draft/importDXF.py", line 2766, in insert
    processdxf(doc, filename)
  File "/tmp/.mount_FreeCAXl4oNg/usr/Mod/Draft/importDXF.py", line 2136, in processdxf
    drawing = dxfReader.readDXF(filename)
  File "/home/pde/.local/share/FreeCAD/Macro/dxfReader.py", line 399, in readDXF
    (infile, drawing) = sm.run((infile, None))
<class 'TypeError'>: cannot unpack non-iterable bool object
```

Same test, but with the new DXF importer succeeds !
![image](https://github.com/easyw/kicadStepUpMod/assets/3703938/c4f99826-0075-4c2a-8a1b-3e5ebe1eab2f)

**Comment by easyw** [comment]
@HaydenHu 
from your error log, it seems you have a Macro named: `dxfReader.py`
in: `/home/pde/.local/share/FreeCAD/Macro/dxfReader.py`
which is interfering with the legacy FreeCD dxf importer

**Comment by DeepCoreSystem** [comment]
@easyw 
Here is the output of your question:
```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:55:59) [GCC 12.3.0] on linux
Type 'help', 'copyright', 'credits' or 'license' for more information.
>>> import importDXF
>>> print(importDXF.CURRENTDXFLIB)
1.41
>>> 
```

**Comment by DeepCoreSystem** [comment]
@easyw 
I found the following at FreeCAD Github: [DXF import issue](https://github.com/FreeCAD/FreeCAD/issues/9817#issuecomment-1622098772)
But I don't get a clue from it ...

**Comment by easyw** [comment]
> edit: I removed the macro `dxfReader.py` in `/home/pde/.local/share/FreeCAD/Macro/` ... but it didn't help

did you restart FreeCAD?
it is strange I don't have issues with FC:
[code]
OS: Windows 10 build 18363
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33992 (Git)
Build type: Release
Branch: master
Hash: 90bafb3a069468455d8c65d030ef8750b510c39b
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
[/code]

**Comment by DeepCoreSystem** [comment]
@easyw 
I contacted Yorik van Havre about the legacy importer, and [his answer](https://github.com/FreeCAD/FreeCAD/issues/9817#issuecomment-1695612189) got me an idea 👍🏼 

I downloaded the V1.40 of the Legacy DXF importer and forced FreeCAD 0.21 to use it. And then I was able to load the silkscreen for a PCB with KiCadStepUp !

**Comment by Ing-Dom** [comment]
I have the same issue.
How di I do that @DeepCoreSystem  ?

> I downloaded the V1.40 of the Legacy DXF importer and forced FreeCAD 0.21 to use it

Or would changing to FreeCad 0.21.0 solve the issue?

**Comment by DeepCoreSystem** [comment]
@Ing-Dom 
Switching to FreeCAD 0.21 doesn't help. The problem is in the Legacy DXF importer V1.41, which you see is downloaded in your log above.

Are you on a Windows machine? It is a little bit convoluted to get the workaround going... The steps below are based on Windows directories ... This worked for me, but I take no responsibility for you!

1. Disable in FreeCad the option to automatically download the DXF library
![image](https://github.com/easyw/kicadStepUpMod/assets/3703938/537984be-72d4-4a7c-8a29-c871c5e3fa5c)
2. Terminate FreeCAD
3. In the path `C:\Users\{your_username}\AppData\Local\Programs\FreeCAD 0.21\Mod\Draft` modify the file `importDXF.py`. In Line 51 set `CURRENTDXFLIB = 1.40` (normally, there is 1.41)
![image](https://github.com/easyw/kicadStepUpMod/assets/3703938/c6a1183b-6582-4dad-a8c9-f608aa35fbf9)
5. In path `C:\Users\{your_username}\AppData\Roaming\FreeCAD\Macro` delete the folder `__pycache__` and put the V1.40 Legacy DXF library from GitHub there
![image](https://github.com/easyw/kicadStepUpMod/assets/3703938/ffdca548-ac58-489a-a5b6-d8a754919255)


The modification in Step 3 is to prevent FreeCAD from wanting to download V1.41 and giving a warning about it.
`10:15:58 DXF libraries need to be updated. Trying to download...`

**Comment by DeepCoreSystem** [comment]
I opened an issue at FreeCAD repository:  [[Problem] Legacy DXF importer with Draft-dxf-importer V1.41 breaks KiCadStepUp WB #10554](https://github.com/FreeCAD/FreeCAD/issues/10554)

**Comment by Ing-Dom** [comment]
@DeepCoreSystem 
Thanks, that worked for me.

I did **not** change CURRENTDXFLIB = 1.40, it worked but with a warning.

**Comment by KSRandD** [comment]
I am trying KicadStepUp out for the first time and have this error on a fresh install of  FreeCAD 0.21 (first time using FreeCAD)
 
In order to get @DeepCoreSystem's workaround to work, I had to use the FreeCAD\mod path, instead of the freeCAD\macro path listed in step 4. 

 The path in step 4 that worked for me : 
`C:\Users\{your_username}\AppData\Roaming\FreeCAD\Mod`

Thanks for the workaround!

**Comment by DeepCoreSystem** [comment]
@Ing-Dom @KSRandD 
Thanks for confirming that there is something broken with V1.41 of the Legacy DXF importer !

About the paths, it seems to depend on which version of FreeCAD and how it was installed.
And also FreeCAD 0.20 is concerned by this problem. I did try it last week with a virtual machine :(

**Comment by leoheck** [comment]
I am also experiencing the same problem.

**Comment by easyw** [comment]
@DeepCoreSystem @HaydenHu 
FC should now handle also kicad dxf files

**Comment by easyw** [comment]
hi to all,
with this commit https://github.com/easyw/kicadStepUpMod/commit/f8d2ff3950e407b574ea91daca5cd3d94e72d42b
kSU is using the old dxf v1.4.0 legacy lib (now incuded in kSU WB) to create silkscreen patterns... also settings are internally handled.
This issue should be closed then.

**Comment by Woodenfishs** [comment]
[谷歌翻译]我想我遇到的问题跟各位差不多，我换了一种方式解决。你可以在KiCad 导出DXF后，使用LibreCAD打开，修改一些无关部分，并且另存为另一个DXF，使用这个DXF导入到FreeCad.
[Google Translate] I think the problem I encountered is similar to everyone else. I solved it in a different way. You can export the DXF from KiCad, open it with LibreCAD, modify some irrelevant parts, save it as another DXF, and use this DXF to import it into FreeCad.
