### ISSUE TITLE
Rotation of footprint is wrong when loaded in ksu

### ISSUE THREAD

**Issue by dennevi** [easyw/kicadStepUpMod#183]
In KiCad 7.0.7 the footprint looks like this:
![image](https://github.com/easyw/kicadStepUpMod/assets/6086066/b7a00f59-ccda-48ea-97e4-9ec9addd2f6d)
But when loaded into ksu 10.8.7 everything but the two holes have been rotated:
![image](https://github.com/easyw/kicadStepUpMod/assets/6086066/69031962-fa79-4771-a599-df7506d3eda2)
Here's the footprint with .txt added to the filename: [HM-AMP-1473005-1.kicad_mod.txt](https://github.com/easyw/kicadStepUpMod/files/12673108/HM-AMP-1473005-1.kicad_mod.txt)

I've also noticed the same thing problem with this footprint: [HM-ALUCAP-D10x10.5.kicad_mod.txt](https://github.com/easyw/kicadStepUpMod/files/12673128/HM-ALUCAP-D10x10.5.kicad_mod.txt)
In this case everything is rotated, I guess because the footprint doesn't have any holes. It has the effect that the STEP and WRL files that are exported from KSU has to be rotated in KiCad to fit the footprint.
KiCad: 
![image](https://github.com/easyw/kicadStepUpMod/assets/6086066/347b209b-9bf5-4fac-b9c8-aa07d16b585a)
KSU: 
![image](https://github.com/easyw/kicadStepUpMod/assets/6086066/be98d0b2-9bc8-4330-b9b0-54740012d3c5)

Thanks for a really great tool! I just started using it today.

**Comment by easyw** [comment]
Hi,
the rotation is related to the 3D model settings in kicad... but probably it is better to just load the fp as in kicad and simply warn the user in case of rotations

**Comment by dennevi** [comment]
> the rotation is related to the 3D model settings in kicad

Thank you! Setting the Z rotation to 0 in the footprint before importing it into FreeCad gave me the expected behavior and a much better workflow. 

> probably it is better to just load the fp as in kicad

Yes, if you ask me. I don't see why one would want the footprint to be rotated when working with 3d models for footprints. I'm not even sure that the warning is needed.

**Comment by easyw** [comment]
@dennevi 
I have updated the tool... it should now read correctly the fp

**Comment by dennevi** [comment]
Works really good! I've tried it with 5-6 footprints that has a rotated 3D model and a few that doesn't. Works every time and the warning only shows up when it should.

Thanks a bunch!
