### ISSUE TITLE
What is attribute 'RedundantConstraints' & why is it suddenly needed?

### ISSUE THREAD

**Issue by cdntinker** [easyw/kicadStepUpMod#194]
Opened FreeCAD today & it told me I needed to update KiCad StepUp...

Linux (LMDE5)
FreeCAD (0.19)
kicadStepUp (10.9.6)  (is it me? or did the versioning go in reverse?)

Now, attempting to add tracks results in:

`15:23:03  Running the Python command 'ksuToolsAddTracks' failed:
Traceback (most recent call last):
  File "/home/tinker/.FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 4352, in Activated
    add_toberemoved = tracks.addtracks()
  File "/home/tinker/.FreeCAD/Mod/kicadStepUpMod/tracks.py", line 616, in addtracks
    if len (pcb_sk.RedundantConstraints)>0:

'Sketcher.SketchObject' object has no attribute 'RedundantConstraints'`

**Comment by easyw** [comment]
FreeCAD (0.19) is an old release...
the actual stable is 0.21 which is working with... (it is possible to use FC AppImage in LMDE5)
anyway I added the code to be retro compatible,  but keeping the best approach on actual FC release.
