### ISSUE TITLE
wrong orientation of holes from footprint

### ISSUE THREAD

**Issue by MasteringTheMess** [easyw/kicadStepUpMod#199]
I have a connector that adds two holes in the pcb for positioning.
When I import this board into FreeCad via Kicad stepup the orientation of the holes is wrong if I rotate the footprint:

![image](https://github.com/easyw/kicadStepUpMod/assets/85557472/be26572b-8731-4ce1-a964-d514a001689d)
![image](https://github.com/easyw/kicadStepUpMod/assets/85557472/e8656ae4-1fae-498d-b281-bfa873182c97)

It's fine in the KiCad 3D-Viewer though:
![image](https://github.com/easyw/kicadStepUpMod/assets/85557472/855216a8-48fe-452c-95a5-b9f942f84b19)

Heres the pcb-file:
[StepUp_test.zip](https://github.com/easyw/kicadStepUpMod/files/13363171/StepUp_test.zip)

**Comment by easyw** [comment]
@MasteringTheMess 
thanks for the testing file...
it should be solved now
https://github.com/easyw/kicadStepUpMod/commit/4f207d1646bb49606f42997bfb7d126592804d00

**Comment by MasteringTheMess** [comment]
Can confirm it works now, Thanks!

Just for the record: the problem did not occur when NPTH were used instead of edge cutouts
