### ISSUE TITLE
Preferences option missing & crash on pcb import

### ISSUE THREAD

**Issue by JustClaireee** [easyw/kicadStepUpMod#20]
Unable to set up StepUp preferences as the option is missing.

Heres the screenshot 
![image](https://user-images.githubusercontent.com/47453559/58748482-31585c00-8482-11e9-96c8-9f9a7018fcb8.png)

Freecad is also not responding when i try to open a Kicad PCB from file menu.

**Comment by easyw** [comment]
This is normal for FreeCAD.
You need to switch to KicadStepUp wb at least one time after FC has started to make the preferences visible in FC pref dialog.

**Comment by JustClaireee** [comment]
So i just need to wait till the preferences menu shows up? Sorry im new to freecad XD

**Comment by JustClaireee** [comment]
Oh, found out what i need to do!)
Ty for help)

**Comment by easyw** [comment]
You need to switch to kicadStepUp wb in FC and then you will find that stepup will be available in FC pref dialog.
