### ISSUE TITLE
"Add Tracks" error : "DLL load failed...invalid access"

### ISSUE THREAD

**Issue by avsteele** [easyw/kicadStepUpMod#212]
KiCAD: 7.0.10
FreeCAD: 0.21.2

A recent PCB import correctly, but when trying to "Add Tracks" it errors out.  I have not used the add on much but a simpler board didn't have a problem

Crash log is attached
[stepUp_error.txt](https://github.com/easyw/kicadStepUpMod/files/14653541/stepUp_error.txt)

It looks like it got all the pads, or close to it, then had a problem when it tried to move them into position at/near the end.

![image](https://github.com/easyw/kicadStepUpMod/assets/25284525/d255099f-d97e-40a9-8901-658ff94aeb23)

Thanks for writing the addon and and maintaining it!

**Comment by easyw** [comment]
@avsteele 
could you please add the board that is failing? (zipped)
I cannot reproduce your issue in 
[code]
OS: Windows 10
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * kicadStepUpMod 10.23.2
[/code]
and please add your full FC and kSU versions

**Comment by avsteele** [comment]
Board attached (just the `.kicad_pcb` file) as well as a new copy of the log file showing the error

Reproduced by:
1) Open FreeCAD
2) Load KSU workbench
3) Import board (works fine)
4) import tracks -> **error**

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Help 1.0.3
  * kicadStepUpMod 11.1.0
  * Manipulator 1.5.7
```

Thanks!

[stepup_import_tracks_error.txt](https://github.com/easyw/kicadStepUpMod/files/14695125/stepup_import_tracks_error.txt)
[stepup_import_tracks_error.zip](https://github.com/easyw/kicadStepUpMod/files/14695126/stepup_import_tracks_error.zip)

**Comment by easyw** [comment]
@avsteele 
Thanks for the kicad test file.
I confirm I cannot replicate the issue.
From your log it seems there is an issue with importing TechDraw WB
` File "C:\Program Files\FreeCAD 0.21\Mod\Draft\draftobjects\shape2dview.py", line 343, in execute
    obj.Shape = self.getProjected(obj,obj.Base.Shape,obj.Projection)
  File "C:\Program Files\FreeCAD 0.21\Mod\Draft\draftobjects\shape2dview.py", line 149, in getProjected
    import TechDraw
  File "C:\Program Files\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ImportError'>: DLL load failed while importing TechDraw: Invalid access to memory location.`

So it seems to me more an issue in FC installation environment instead an issue of kSU WB.
I tried with 
> FreeCAD-0.21.2-WIN-x64-installer-1.exe

downloaded from FC main web page:
https://github.com/FreeCAD/FreeCAD/releases/download/0.21.2/FreeCAD-0.21.2-WIN-x64-installer-1.exe

**Comment by avsteele** [comment]
I confirm that appears to be is the same installation file I used. I may try to reinstall. If this changes things I will update the issue.

**Comment by easyw** [comment]
@avsteele 
could you please try to execute this code in FC python console?

`import TechDraw`

**Comment by avsteele** [comment]
@easyw The import completes without error. I decided to retry the loading today and it completes without error! I tried it multiple times. I have no explanation.  I haven't updated KiCAD or changed my mods

Please feel free to close the issue. If it recurs i will try to gather more information.

Thank you for your continued support of this mod (an 'Manipulator, which I also am using)
