### ISSUE TITLE
Invalid ambientIntensity value for GLASS-19 material

### ISSUE THREAD

**Issue by adamalfath** [easyw/kicadStepUpMod#215]
The issue was found by another developer (https://github.com/fougue/mayo/issues/268) while I was trying a 3d viewer program.

From quick reading, the ambientIntensity value per VRML 2.0 specification should be in the range of 0.0 to 1.0?

**Comment by easyw** [comment]
@adamalfath 
could you please post a sample of the vrml file?
which is the wrong value?

**Comment by adamalfath** [comment]
Here is the example file: [LCM_ZJY096T-IG11.zip](https://github.com/easyw/kicadStepUpMod/files/14990700/LCM_ZJY096T-IG11.zip) line 270 `ambientIntensity 2.018212`

Since the material definition is automatically generated from KSU, it will be present on every VRML output file.

**Comment by easyw** [comment]
thanks, but which is the correct ambientIntensity value to be applied?
