### ISSUE TITLE
PySide2 deprecated, addon does not work on Archlinux

### ISSUE THREAD

**Issue by Kezii** [easyw/kicadStepUpMod#217]
`02:10:54  During initialization the error "No module named 'PySide2'" occurred in /home/[...]/.local/share/FreeCAD/Mod/kicadStepUpMod/./InitGui.py`

Apparently PySide2 is EOL and works only with older versions of python

https://code.qt.io/cgit/pyside/pyside-setup.git/log/?h=5.15.2
https://wiki.qt.io/Qt_for_Python

Project should migrate to PySide6

**Comment by easyw** [comment]
hi @Kezii 
which is your kSU version?
Anyway, following your issue I searched for all instances of PySide2 and I removed all of them with the latest commit...

**Comment by Kezii** [comment]
the latest installing with the addon manager, now I updated and the addon appears, thank you
