### ISSUE TITLE
Kicad StepUp Issue Exporting STEP files in FreeCAD Version 1.0

### ISSUE THREAD

**Issue by tinkrelectronic** [easyw/kicadStepUpMod#234]
If object to export has more than 1 colour - the step file results in an invisible object in KiCad, the object is there, but something is wrong with the step file, I imported a STEP to double check, same result.

FreeCAD 0.21.2 does not have this issue

**Comment by easyw** [comment]
@tinkrelectronic 
please post FC file and step file that are failing.

**Comment by tinkrelectronic** [comment]
I was able to fix this by completely removing everything and reinstalling. Something about running 0.21 and 1.0 seemed to have broke it.
