### ISSUE TITLE
Antenna Footprint

### ISSUE THREAD

**Issue by leoheck** [easyw/kicadStepUpMod#24]
Hi, I am importing the board tracks, but I have some footprints with some tracks F.cu and B.cu tracks. For example, I have a trace PCB antenna which is not imported with the tracks with the Add Tracks command. Do you have any alternative to import tracks in footprints?

**Comment by easyw** [comment]
Hi,
footprint with tracks are not allowed by kicad... those can be done as a hack.
I would suggest to use a poly-line pad to design your antennas...
Please have a look at the files inside StepUp demo menu.
https://github.com/easyw/kicadStepUpMod/blob/master/demo/footprint-RF-antenna.FCStd
https://github.com/easyw/kicadStepUpMod/blob/master/demo/footprint-RF-antenna-w-solder-Mask.FCStd
![image](https://user-images.githubusercontent.com/3032347/64130035-00106480-cdc0-11e9-9f73-d7f5573b1a63.png)

**Comment by morganrallen** [comment]
FWIW, I believe future versions of KiCAD will support non-pad copper in footprints. I could be mistaken but I recall hearing something along these lines at KiCON.

**Comment by easyw** [comment]
Antenna normally are designed from a mechanical sw ... typically you can find antenna models in DXF format... the DXF format is also used by most RF simulation sw...
then the best option is to convert the DXF to a sketch and then use it to export the model as a poly-line pad for kicad.

**Comment by leoheck** [comment]
Thanks for the workaround @easyw 

The antenna I want to export was made by my in Kicad, and I was not able to export .dxf files from the Library Editor.

I actually filed an issue today. Regarding exporting a .dxf from Library Editor.
https://bugs.launchpad.net/kicad/+bug/1842348

**Comment by easyw** [comment]
You can simply export a board with your antenna fp as DXF, and then extract your data from the resulting DXF.

**Comment by easyw** [comment]
FYI here some Ti antenna DXF shapes
[CC_2D00_Antenna_2D00_DK2.dxf](https://e2e.ti.com/cfs-file/__key/communityserver-discussions-components-files/538/CC_2D00_Antenna_2D00_DK2.dxf)

**Comment by luzpaz** [comment]
> I actually filed an issue today. Regarding exporting a .dxf from Library Editor. https://bugs.launchpad.net/kicad/+bug/1842348

JFYI @leoheck, your upstream ticket has moved to https://gitlab.com/kicad/code/kicad/-/issues/2493
