### ISSUE TITLE
Imported STEP in Fusion 360 has no track/silk color on bottom layer

### ISSUE THREAD

**Issue by TinusScheppers** [easyw/kicadStepUpMod#25]
The STEP file is created by exporting a PCB+Tracks+Silk using FreeCAD.

When importing this step model in Fusion it seems that the color reverts to (default?) copper for all items except the PCB.

However when importing the STEP file back in FreeCAD everything is in the correct color.

Is there something that can be done to correct/change this behaviour?

Example: 
Front in FreeCAD
![afbeelding](https://user-images.githubusercontent.com/2527506/66272436-fa4bea00-e869-11e9-93e5-9b6b83be1197.png)

Front in Fusion
![afbeelding](https://user-images.githubusercontent.com/2527506/66272447-1780b880-e86a-11e9-88e9-c2c8078a77f9.png)
=> Behaviour as expected

Back in FreeCAD:
![afbeelding](https://user-images.githubusercontent.com/2527506/66272458-3a12d180-e86a-11e9-92f4-9ce334a399c4.png)

Back in Fusion:
![afbeelding](https://user-images.githubusercontent.com/2527506/66272460-49921a80-e86a-11e9-8548-cf57ea5428c9.png)
=> Behaviour not as expected

Please find the STEP file attached:
[Front.zip](https://github.com/easyw/kicadStepUpMod/files/3694656/Front.zip)

**Comment by TinusScheppers** [comment]
In addition: I just noticed that when creating a mirrored version (in Fusion), the original(!) gets the correct colors (the mirrored version still has the wrong colors)...

**Comment by easyw** [comment]
Hi @TinusScheppers 
this seems an issue in Fusion360 STEP importing function.
You can try to open the file with [CAD Assistant](https://www.opencascade.com/content/cad-assistant) or with [DesignSparkMechanichal](https://www.rs-online.com/designspark/mechanical-download-and-installation) and there are no issue.

**Comment by TinusScheppers** [comment]
> 
> 
> Hi @TinusScheppers
> this seems an issue in Fusion360 STEP importing function.
> You can try to open the file with [CAD Assistant](https://www.opencascade.com/content/cad-assistant) or with [DesignSparkMechanichal](https://www.rs-online.com/designspark/mechanical-download-and-installation) and there are no issue.

Indeed, definitely an issue in Fusion given the above workaround.
Anyway, I was hoping maybe you had an idea what the cause might have been, but its more of a problem for the Fusion 360 developers.
Maybe I'll post it over there.

Keep up the good work, this is a great tool!

**Comment by jacobtohahn** [comment]
@Devenda, did you ever find a solution for this issue anywhere? I have the exact same problem and I'm not sure how or if I can resolve it.

**Comment by Devenda** [comment]
@jacobtohahn, The best I could find was a workaround.

It was possible to create a mirror of the offending piece, strangely enough this made the original piece appear as expected.
After this the (new) mirrored piece can be removed. (You will see that the mirrored piece again has the color).

![afbeelding](https://user-images.githubusercontent.com/2527506/89103257-b2a5d880-d410-11ea-9146-e833acc58c1c.png)

Good luck!

**Comment by jacobtohahn** [comment]
Interesting. Glad the workaround is that simple.
