### ISSUE TITLE
Draw EP pad as circle

### ISSUE THREAD

**Issue by jneiva08** [easyw/kicadStepUpMod#3]
Hi,

I was try to verify if a 3d step was matching with the footprint.
When the [footprint](https://github.com/KiCad/kicad-footprints/blob/master/Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP7.7x7.7mm.kicad_mod) loaded show the EP pad as circle instead a square with rounded corners.

![qfn_64_7x7](https://user-images.githubusercontent.com/8236353/41935307-153601ec-7981-11e8-8236-b0614f2fab52.png)

Now with thermal via.
![qfn_64_7x7_thermal](https://user-images.githubusercontent.com/8236353/41935311-1b3bdd8c-7981-11e8-8bb0-b38b593beda9.png)

I opened this issue only to report.

Thanks, for a usefull addon.

**Comment by poeschlr** [comment]
I would guess that the footprint in question had rounded rectangle pads.
Not sure why sometimes rounded rectangle is converted to a circle and sometimes to a rectangle.

As the particular footprint in question no longer exists in the lib, here the link to this footpirnt from the lib tagged as 5.0.0-rc3: https://github.com/KiCad/kicad-footprints/blob/5.0.0-rc3/Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP7.7x7.7mm.kicad_mod

**Comment by poeschlr** [comment]
@easyw would it be easily possible to just interpret rounded rectangle pads as rectangle pads until proper support for rounded rectangle pads is added? (This would allow checking of footprint dimensions for such parts even if it does not fully represent the finer details of the footprint)

**Comment by easyw** [comment]
@jneiva08 @poeschlr 
it seems it was not so long to implement 😄 
![rrect](https://user-images.githubusercontent.com/3032347/43360850-03e0afca-92c0-11e8-8e88-e45cfe86dbc2.png)

Please update the ksu WB (actual release 7.3.3.3).

**Comment by poeschlr** [comment]
Wow. Thanks for the update.

**Comment by jneiva08** [comment]
Thanks for fix it
