### ISSUE TITLE
Error on imported FP with rotated oval pads

### ISSUE THREAD

**Issue by Shackmeister** [easyw/kicadStepUpMod#36]
Pad from affected FP:
`(pad 1 thru_hole oval (at -3.7338 0 115) (size 3.3 1.5) (drill oval 2.7 0.9) (layers *.Cu *.Mask))`
![KSU_Oval pad](https://user-images.githubusercontent.com/5279723/72392003-3a571e80-372f-11ea-8078-4de666e3ff8a.png)

**Comment by easyw** [comment]
@Shackmeister 
is your wb uptodate?
it should be already solved...
https://forum.kicad.info/t/stepup-error-viewing-footprint-with-pads-having-custom-orientation-solved/20672/7

fixing bottom pad fp rotation
[easyw committed 2 days ago
](https://github.com/easyw/kicadStepUpMod/commit/49d1487268747ed418286d3cf1adcc98c8839d35)

**Comment by Shackmeister** [comment]
Oops, sorry for the noise
