### ISSUE TITLE
3D object to 2D projection is flipped

### ISSUE THREAD

**Issue by jeremyherbert** [easyw/kicadStepUpMod#39]
As a learning example, I'm trying to create a footprint for the following part: https://www.sparkfun.com/products/9032 (there is a STEP model available on that page).

I started by importing the model, changed the view to the bottom of the part (using the cube in the corner) and then selected the joystick object and clicked "3D object to 2D projection". However, the resulting projection is both rotated and flipped. Am I doing something wrong here?

![FreeCAD_0_18](https://user-images.githubusercontent.com/52499/73602054-b323fa80-45b8-11ea-9b33-80b505580614.png)

**Comment by easyw** [comment]
@jeremyherbert 
ksu is using a FC function to make the projection... 
https://www.freecadweb.org/wiki/Draft_Shape2DView
Moreover it may be related to OCC Kernel..
so the issue should be reported at FC repo.
ATM you can workaround it simply rotating and aligning the projection.

**Comment by jeremyherbert** [comment]
This is not an issue here, so closing

**Comment by jeremyherbert** [comment]
Just reporting on what the actual issue is and a workaround:

workaround: https://forum.freecadweb.org/viewtopic.php?f=22&t=24807&p=194839#p194816

issue: https://tracker.freecadweb.org/view.php?id=3348
