### ISSUE TITLE
Failed to export to kicad with scale 1/2.54

### ISSUE THREAD

**Issue by syed93uthman** [easyw/kicadStepUpMod#4]
![image](https://user-images.githubusercontent.com/3021303/41951881-b707e8a4-79ff-11e8-8b63-3daa3c348fc5.png)

Im not sure what im doing wrong but this failed report keep appear on the report view.

**Comment by easyw** [comment]
Hi, you are trying to export a mesh object. StepUp is working with solid objects ... you should use a STEP file to make your conversion.
