### ISSUE TITLE
Add new feature to import PCB inner layer

### ISSUE THREAD

**Issue by rniueng** [easyw/kicadStepUpMod#40]
Now the Top and Bottom layers of PCB can be imported to Freecad. This is good enough for mechanical design. For some purposes, all inner layers of PCB need to be imported to 3D tool. Is there any way to do this weith StepUpMod? or could consider to add this feature.

**Comment by easyw** [comment]
> For some purposes, all inner layers of PCB need to be imported to 3D tool.
@rniueng 
which is your purpose?

**Comment by laurencedv** [comment]
Maybe for EM or thermal analysis in another FreeCAD workbench (I'm not the OP so I dont know, but that could be a very useful feature)

**Comment by easyw** [comment]
You may need to look at @realthunder fcad_pcb tools 
https://github.com/realthunder/fcad_pcb

**Comment by rniueng** [comment]
One purpose is to use the exported layers to describe trace routing strategy for training and documentation. In FreeCAD, I can enable disable layer easily and make PCB (FR4) material Transparent so inner layer can be viewed. Also I can change the color for any trace.

The other thing is EM simulations. I want to analyze trace to trace inductance and capacitance.

I’m getting help from real thunder too on my installation issue. I haven’t successfully run the fc_pcb tool. That is nice tool for me too.

Thanks

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: easyw <notifications@github.com>
发送时间: Thursday, February 20, 2020 4:03:17 AM
收件人: easyw/kicadStepUpMod <kicadStepUpMod@noreply.github.com>
抄送: rniueng <rniueng@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [easyw/kicadStepUpMod] Add new feature to import PCB inner layer (#40)


Closed #40<https://github.com/easyw/kicadStepUpMod/issues/40>.

―

**Comment by Quas7** [comment]
+1
usecase: designing a PCB coil and running ElmerFEM magnetodynamic simulations on it.
Thanks for the tip with fcad_pcb. That seems to be the best route for now.
