### ISSUE TITLE
footprint missing one pad

### ISSUE THREAD

**Issue by jeremyherbert** [easyw/kicadStepUpMod#46]
I'm using this addin with FreeCAD 0.18-16146. When I try to export a footprint from the attached file, I am missing one pad and I am not sure why?

![Footprint_Editor](https://user-images.githubusercontent.com/52499/78746201-8f5ea580-79a9-11ea-890b-eb3b4cf85a9a.png)

[footprint.FCStd.zip](https://github.com/easyw/kicadStepUpMod/files/4448260/footprint.FCStd.zip)

**Comment by easyw** [comment]
@jeremyherbert 
the converting algo is quite simple and requires a strait sequence of edges.
The missing pad has a wrong edge sequence.
Anyway I would suggest you to use the rectangle tool to create pads instead of placing 4 lines together
![rectangle-tool](https://user-images.githubusercontent.com/3032347/78942105-4269f480-7ab9-11ea-96b5-1626ed8baab3.png)
.
Here the fixed file.
[footprint-fixed.zip](https://github.com/easyw/kicadStepUpMod/files/4458705/footprint-fixed.zip)

**Comment by jeremyherbert** [comment]
Thanks! I actually created this using a DXF import and then the DXF to sketch feature. Is there a way to have this convert the lines into rectangles?

[pads.dxf.zip](https://github.com/easyw/kicadStepUpMod/files/4459420/pads.dxf.zip)

**Comment by easyw** [comment]
@jeremyherbert 
have you used the StepUp button to convert the imported dxf shapes?
![2d-to-dxf](https://user-images.githubusercontent.com/3032347/78966010-ff327480-7afe-11ea-99a8-c621b4a49255.png)

for me, using this button, it just worked
[pads-dxf-to-sketch.zip](https://github.com/easyw/kicadStepUpMod/files/4460063/pads-dxf-to-sketch.zip)

**Comment by jeremyherbert** [comment]
Yes, that is the button I used. I tried it several times too... I will try to investigate further

**Comment by jeremyherbert** [comment]
I just tried this again:

1. Create a new document in FreeCAD
2. File => Import, browse to the `pads.dxf` file and open
3. Select all of the entities that were imported and click the "2D object (or DXF) to Sketch" button
4. Delete the entities, leaving just the sketch behind
5. Rename the sketch to "Pads_TH_SMD"
6. Select the sketch and click "Footprint editor and exporter"
7. Save the mod file
8. Open in Kicad 5.1.5

This time it has given me different missing pads? I think I am going to try to install the freecad beta as it seems you are running a newer version that I am 

[test.kicad_mod.zip](https://github.com/easyw/kicadStepUpMod/files/4463881/test.kicad_mod.zip)
[new.FCStd.zip](https://github.com/easyw/kicadStepUpMod/files/4463882/new.FCStd.zip)

![footprint](https://user-images.githubusercontent.com/52499/79032433-c1f6e100-7be9-11ea-85a0-47e7494e36c5.png)

**Comment by jeremyherbert** [comment]
Ok, it looks like when I use the freecad version from here: https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre it has worked fine three times in a row. So I suppose this is due to a bug in freeCAD.

Shall I close this issue, or is it better to wait until 0.19 is released?

**Comment by easyw** [comment]
We can leave it open until 0.19 will be released as stable. 
Thx

**Comment by jeremyherbert** [comment]
I have unfortunately encountered this problem again, even using the latest freecad. Could you point me toward the section of the code that does the pad detection? I could perhaps try to fix this myself.

This file has the center pad missing when converted to a kicad footprint.

[pads.dxf.zip](https://github.com/easyw/kicadStepUpMod/files/4526029/pads.dxf.zip)

**Comment by easyw** [comment]
@jeremyherbert 
the routine is called
