### ISSUE TITLE
SilkS layer out of the board

### ISSUE THREAD

**Issue by leoheck** [easyw/kicadStepUpMod#49]
@easyw easyw, this plugin is getting better and better. This is awesome, thank you for that.

This is one thing that I would like to give as the feedback since some time ago.

What do you think to have something that cuts the silkscreen (removing parts that are not over the board). Please, have a look at the following example.

![image](https://user-images.githubusercontent.com/1277920/82742835-25237980-9d39-11ea-9e16-058d901c637b.png)

I don't know if this is too much of work since right now, I was not able to import the SilkS in the right position in the first place. But you can tell this better.

**Comment by easyw** [comment]
> I was not able to import the SilkS in the right position in the first place.

Please have a look at here: https://forum.kicad.info/t/stepup-silkscreen-in-wrong-location/22471/3

> What do you think to have something that cuts the silkscreen (removing parts that are not over the board).

the wanted result could be obtained in FC with a common boolean operation between Silks and pcb, but this is a bit out of scope here
The best for this option is to be implemented directly in KiCAD ...

**Comment by leoheck** [comment]
Cool thanks. I was also doing this on Freecad, it is easy, but it is better if it can be automated, right? I will file a feature request on Kicad.

**Comment by leoheck** [comment]
This issues was already there on kicad repo.
https://gitlab.com/kicad/code/kicad/-/issues/2293
