### ISSUE TITLE
Can't export poly pad with oval hole

### ISSUE THREAD

**Issue by sambazley** [easyw/kicadStepUpMod#52]
I'm creating a footprint for a USB port that requires two poly pads, each with an oval hole. The footprint fails to export with:

```
Running the Python command 'ksuToolsFootprintGen' failed:
Traceback (most recent call last):
  File "/home/user/.FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 1920, in Activated
    kicadStepUptools.PushFootprint()
  File "/home/user/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 16551, in PushFootprint
    sk_d=Draft.makeSketch([wns,wnc[0]])

list index out of range
```

[usb.zip](https://github.com/easyw/kicadStepUpMod/files/4906203/usb.zip)

**Comment by easyw** [comment]
@sambazley 
you need to make the pads with a workaround
here the files
[USB_Micro-B-modified.zip](https://github.com/easyw/kicadStepUpMod/files/4909351/USB_Micro-B-modified.zip)

**Comment by sambazley** [comment]
That works, but it results in one of the poly pads covering the hole in the 3D viewer.
![img](https://user-images.githubusercontent.com/9405821/87256669-a6230580-c48c-11ea-8e20-6086af3e0535.png)

It displays correctly on the back of the board though.
![image](https://user-images.githubusercontent.com/9405821/87256691-d4a0e080-c48c-11ea-972a-8957c0dca287.png)

I tried to fix this by using a poly pad that doesn't cover the hole, but this pad doesn't show up at all in Kicad.
![image](https://user-images.githubusercontent.com/9405821/87257467-1c2a6b00-c493-11ea-9b96-78ec5a6bb960.png)

[usb.zip](https://github.com/easyw/kicadStepUpMod/files/4909661/usb.zip)

Thanks for your help.

**Comment by easyw** [comment]
I just forgot to remove solder paste on one SMD pad:
[usb-micro-b-v2.zip](https://github.com/easyw/kicadStepUpMod/files/4910755/usb-micro-b-v2.zip)

**Comment by sambazley** [comment]
Oh I didn't think to check that. Thank you :)
