### ISSUE TITLE
Error pushing edges

### ISSUE THREAD

**Issue by tclarke** [easyw/kicadStepUpMod#53]
can't push edges 
kicadStepUptools.py:15645 currentTextChanged not a member of QComboBox.
Probably needs to be editTextChanged

**Comment by tclarke** [comment]
> @tclarke
> would you mind to upload the FC file which gives you the error?
> could you please add also FC full information?

Downloaded a fresh copy when initially testing so 0.18.4. Don't recall if that was the version I originally saw the problem but it was no more than a release behind. Windows 10 64-bit.

**Comment by easyw** [comment]
@tclarke so your issue can be closed?

**Comment by tclarke** [comment]
The pull request I sent fixes this issue.

**Comment by easyw** [comment]
@tclarke 
would you please attacha a FC file wich is causing this issue? (just zip it and attach it to a essage)

**Comment by tclarke** [comment]
sorry, just noticed this...I'll put something together

**Comment by easyw** [comment]
@tclarke any news on it?
