### ISSUE TITLE
local variable 'firstCoordinate' referenced before assignment

### ISSUE THREAD

**Issue by morganrallen** [easyw/kicadStepUpMod#55]
Trying to create a complex footprint but fails with `local variable 'firstCoordinate' referenced before assignment`

Even simplified forms fail with the same error.

```
Running the Python command 'ksuToolsFootprintGen' failed:
Traceback (most recent call last):
  File "/home/morgan/.FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 1920, in Activated
    kicadStepUptools.PushFootprint()
  File "/home/morgan/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 16583, in PushFootprint
    export_footprint(name)
  File "/home/morgan/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 17257, in export_footprint
    pth_ordered=collect_pads(pply) #pads_all)  ## pads normalized with sequence of segments
  File "/home/morgan/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 18000, in collect_pads
    if distance(firstCoordinate, nextCoordinate)<=edge_tolerance:# or pad_list[j-1][0]=='circle':

local variable 'firstCoordinate' referenced before assignment

```

[humming_pad.FCStd.gz](https://github.com/easyw/kicadStepUpMod/files/4983624/humming_pad.FCStd.gz)

**Comment by morganrallen** [comment]
I've tried various `Pads_TH_SMD`, `Pads_Round_Rect` but all have the same error. FWIW it would be super handy to have a complete list of the supported Sketch name tags and what they're for.

**Comment by easyw** [comment]
@morganrallen 
for this 'artwork' pad type I would suggest to discretize the sketch (with ksu tool) and then export it as a polyline pad
[humming_pad-discretized.zip](https://github.com/easyw/kicadStepUpMod/files/5002747/humming_pad-discretized.zip)


> FWIW it would be super handy to have a complete list of the supported Sketch name tags and what they're for.

I would accept a user manual contribution, based on the example included with the WB 😉
