### ISSUE TITLE
Add the classic About page

### ISSUE THREAD

**Issue by Franck78** [easyw/kicadStepUpMod#57]
It's far from evident to find the source repository for this project ;)

No need to describe an about page I think.

**Comment by easyw** [comment]
@Franck78 
the help button is not enough for you? (moreover you find it also on help tips in FC StepUp preferences)
from help menu you get directly here and to the kicadStepUp-cheat-sheet.pdf

**Comment by Franck78** [comment]
Just think I'm stupid sheep formated to standard reflexes after 30 years of windowing. I need 'help', I search the menu help.
I want to know who is the author, I search about.
