### ISSUE TITLE
Exporting parts without STEP model

### ISSUE THREAD

**Issue by rush0815** [easyw/kicadStepUpMod#59]
I have many testpoints on my pcb panel and need them to be exported in the STEP-file so that I get the exact position of them to place drills on that pos. 

Is that possible with that version? Or do you have any workaround for me?

**Comment by easyw** [comment]
Do you have a FreeCAD sketch in which you have placed the testpoints or do you need to import them from kicad to FreeCAD?
You can import from kicad to FreeCAD a sketch from the pcbnew file on different layers using the KSU Pull Sketch from pcbnew button. Then from FC you can export a STEP file ...
