### ISSUE TITLE
Imported STEP file, pins projected in odd location. 

### ISSUE THREAD

**Issue by robot-army** [easyw/kicadStepUpMod#68]
Hi, I've imported a step file (attached) and attempted to use this tutorial to extract the pin locations from the model. 

When I try to project the pins (2D object to 3D projection) they show up in a very odd place. Sometimes in the correct orientation, but never overlaid on the plane of the pins. See screenshot and freecad file. 
[i7C_Base_unit_FullFeature.zip](https://github.com/easyw/kicadStepUpMod/files/5706611/i7C_Base_unit_FullFeature.zip)

I've also uploaded a screenshot. 

![image](https://user-images.githubusercontent.com/4554056/102436146-c96a5780-3fcc-11eb-867b-da12ee211295.png)

Thanks

**Comment by easyw** [comment]
@robot-army 
you need to place your model aligned to top view and after that project the pins.

**Comment by easyw** [comment]
@robot-army I'm closing it... feel free to reopen it in case you need.
