### ISSUE TITLE
Line (Track) through identical points warning

### ISSUE THREAD

**Issue by davidsrsb** [easyw/kicadStepUpMod#70]

**Comment by davidsrsb** [comment]
I get a strange warning when I use add tracks
Line (Track) through identical points [132, 149.9]

There is nothing visible on the PCB at that point

I also get five times 20:28:35  <Exception> Access violation after the done copper layer F.Cu

This is a four layer pcb
I can share it confidentially

**Comment by easyw** [comment]
@davidsrsb you can PM me at kicad.info forum attaching your zipped pcb and I will have a look.. thx

**Comment by davidsrsb** [comment]
Did you get the file by forum PM?

**Comment by easyw** [comment]
@davidsrsb 
I (re)checked just now and I have no private message @ kicad.info forum... there I'm the user 'maui'

**Comment by luzpaz** [comment]
@davidsrsb please try to share it again?
