### ISSUE TITLE
Error message should explain how to "assign Grid Origin" in KiCAD pcbnew

### ISSUE THREAD

**Issue by jsmaniac** [easyw/kicadStepUpMod#73]
When I click on `Load KiCad PCB Board and Parts`, I get the following message:

> GridOrigin is set in FreeCAD Preferences but not set in KiCAD pcbnew file
> Please assign Grid Origin to your KiCAD pcbnew board file for a better Mechanical integration

I spent 10 minutes trying to find how to "assign Grid Origin" in KiCAD `pcbnew`'s user interface and couldn't find anything after many Google queries. It seems that it is probably hidden in plain sight… could the error message be updated to indicate how to do so, something like `menu → some menu I didn't find → grid → fill in Grid Origin and click Apply` would be quite helpful :smiley: 

Here's the KiCAD file (just a dummy test) from KiCAD 5.1.5 for which I got that error: [LED.zip](https://github.com/easyw/kicadStepUpMod/files/5762679/LED.zip)

Thank's a lot, the StepUP workbench is impressive!

**Comment by easyw** [comment]
@jsmaniac searching https://duckduckgo.com/?t=lm&q=pcbnew+grid+origin&ia=web, the third result is pcbnew documentation:
https://docs.kicad.org/5.1/en/pcbnew/pcbnew.html
Inside the page search for grid origin and you will find the toolbar... 
Unfortunately Pcbnew is changing toolbar and menus changing versions... 
KiCAD's user has to learn it from the documentation related to the used pcbnew version.
The best is to ask @ KiCAD.info forum 
> Thank's a lot, the StepUP workbench is impressive!

I'm glad you appreciate it...
I'm closing this issue, feel free to reopen it in case of need.
