### ISSUE TITLE
LICENSE file missing in repository

### ISSUE THREAD

**Issue by juancamilog** [easyw/kicadStepUpMod#77]
This repository is missing a license file. I recommend the MIT License.

**Comment by easyw** [comment]
> This repository is missing a license file. I recommend the MIT License.

@juancamilog 
the licence is written in the README file and it is GNU Affero
https://github.com/easyw/kicadStepUpMod/blob/master/README.md
https://www.gnu.org/licenses/agpl-3.0.en.html
