### ISSUE TITLE
Command just to check if 3D model for the imported board exist

### ISSUE THREAD

**Issue by Garuche** [easyw/kicadStepUpMod#81]
Hi,

When importing for the first time or when major updating a board with many component, i think it will be interesting to have a command to fast check if all 3D model of a board are available without importing them.

Your work is great !

Regards,

**Comment by easyw** [comment]
@Garuche 
you may find this tool useful:
https://github.com/easyw/kicad-action-tools/tree/master/checking3Dmodels
