### ISSUE TITLE
Missing plating holes

### ISSUE THREAD

**Issue by HaydenHu** [easyw/kicadStepUpMod#82]
Thank the author for developing this very useful tool, the fly in the ointment is in the output of the trick, thank the author for developing this very useful tool, the fly in the ointment is in the output of the missing plating hole! Can you refer to fcad_pcb The code of PCB tool, make up for this deficiency?

[Missing plating holes](https://forum.kicad.info/t/missing-plating-holes/28744/4)

**Comment by easyw** [comment]
@HaydenHu 
as reported at the kicad info forum:
> this is not planned atm, only mcad integration is fully supported… FEM analysis requires a lot of settings to be useful covered.
