### ISSUE TITLE
Maybe keep-out zones is not working

### ISSUE THREAD

**Issue by savenlid** [easyw/kicadStepUpMod#83]
That is my guess.

[503548-1222.zip](https://github.com/easyw/kicadStepUpMod/files/6329504/503548-1222.zip)

**Comment by easyw** [comment]
@savenlid 
thanks for the fp sample...
this is a fp made in kicad 5.99 ... I'm not supporting all the new features in k nightly ATM, but I see if I cn add the keepout zone to the fp loader.

**Comment by easyw** [comment]
@savenlid 
it should be partially solved... the fp will be loaded but keepout zones will be just dropped

**Comment by savenlid** [comment]
Thank you

much appreciated, I use your tool quite often.

Best regards
/Nicholas



Den mån 19 apr. 2021 kl 12:16 skrev easyw ***@***.***>:

**Comment by easyw** [comment]
@savenlid 
keepout zones are now implemented in fp-loader
