### ISSUE TITLE
Option to export locked edgecut 

### ISSUE THREAD

**Issue by Shackmeister** [easyw/kicadStepUpMod#9]
As title says. For board outlines made in Mcad, it would be nice to make sure they don't get modified in kicad

**Comment by easyw** [comment]
Hi @Shackmeister 
I think this is an option missing in KiCAD... I have not found a way to lock a board edge inside a pcbnew board...
So this should be first implemented in kicad and then stepup would follow.
I think moreover this would need a kicad pcb format change.
