### ISSUE TITLE
Load existing Kicad step modules

### ISSUE THREAD

**Issue by leoheck** [easyw/kicadStepUpMod#96]
Hey @easyw I had an idea here. KicadStepUpMod could integrate a fast way to load Kicad parts into Freecad. Some times I find myself having to model a cable or to test a new part in the board/case. Having an easy way to load existing step modules would be a nice idea. What do you think?

**Comment by easyw** [comment]
@leoheck 
would you please elaborate a bit more?
I cannot understand your requirements
