### ISSUE TITLE
StepUp 10.1.2.0 complains about wrong step files when opening kicad_pcb

### ISSUE THREAD

**Issue by matthiesenj** [easyw/kicadStepUpMod#98]
..the files work without issues when imported directly into FC, though..
I can't say if the files are actually correct or not, just that they work with FC.
Offending files attached.

> 14:39:57  opening C:/Users/Jesper/........./Molex_-_87438-0343.step
> 14:39:57  Molex_-_87438-0343
> 14:39:57  <Import> ImportOCAF2.cpp(541): free shape count 4
> 14:39:57  3D STEP model Molex_-_87438-0343 is WRONG
> 14:41:43  Running the Python command 'ksuToolsOpenBoard' failed:
> Traceback (most recent call last):
>   File "C:\Users\Jesper\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\kicadStepUpCMD.py", line 843, in Activated
>     kicadStepUptools.onLoadBoard()
>   File "C:\Users\Jesper\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 7207, in onLoadBoard
>     Load_models(pcbThickness,modules)
>   File "C:\Users\Jesper\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 4781, in Load_models
>     stop   
> 
> name 'stop' is not defined
> 

[molex-step.zip](https://github.com/easyw/kicadStepUpMod/files/7353492/molex-step.zip)

**Comment by easyw** [comment]
hi @matthiesenj 
it should now be solved with https://github.com/easyw/kicadStepUpMod/commit/b5599f07269461c7ecc05adea2f6a54ea4bb7da6

In general it would help having also a minimal pcb example and the full FC release version
